### ISSUE TITLE
Size of convolutions when using Self-Attention GAN

### ISSUE THREAD

**Issue by wodsoe** [AlexiaJM/relativistic-f-divergences#2]
parser.add_argument('--conv_size', type=int, default=64, help='Size of convolutions when using Self-Attention GAN.')

Hi,how to use Self-Attention GAN?

**Comment by AlexiaJM** [comment]
I tried some PyTorch implementations of self-attention GANs, but they were not like in the self-attention paper and they all worked poorly (I tested them on standard GAN and Hinge GAN, not relativistic), so I ended up deleting them.
