### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Andreababy** [AlexiaJM/relativistic-f-divergences#4]
When i run GAN.py, this question occurs, how to solve it? Thank you!

Traceback (most recent call last):
  File "GAN.py", line 135, in <module>
    os.mkdir(base_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/omnisky/project/relativistic-f-divergences-master/mnt/sdb2/Dropbox/Ubuntu_ML/Output/GANlosses/GAN_-0'

**Comment by AlexiaJM** [comment]
I'm one year too late, but you just need to change your default directories.
